default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: lazy_mtn_development

test:
  <<: *default
  database: lazy_mtn_test

production:
  <<: *default
  database: lazy_mtn_production
